name: Build sandbox

on:
  push:
    branches:
      - main

jobs:
  build-single-binary-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: flyteorg/flyte
      - run: ls

