name: Build sandbox

on:
  push:
    branches:
      - main

jobs:
  build-single-binary-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: flyteorg/flyte

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Go Build Cache for Docker
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            go-build-cache
            go-mod-cache
          key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}

      - name: inject go-build-cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.0
        with:
          cache-map: |
            {
              "go-build-cache": "/root/.cache/go-build",
              "go-mod-cache": "/root/go/pkg/mod"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Setup destination directories for image tarballs
        run: |
          mkdir -p docker/sandbox-bundled/images/tar/amd64

      - name: Build and save
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          push: false
          platforms: linux/amd64
          tags: flyte-binary:sandbox
          outputs: type=docker,dest=docker/sandbox-bundled/images/tar/amd64/flyte-binary.tar
          build-args: |
            FLYTECONSOLE_VERSION=latest
            FLYTE_VERSION=latest

      - name: Upload single binary image
        uses: actions/upload-artifact@v2
        with:
          name: single-binary-image
          path: docker/sandbox-bundled/images/tar
